# Generated by Django 6.0.2 on 2026-02-07 22:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='chamado',
            options={'ordering': ['-data_criacao'], 'verbose_name': 'Chamado', 'verbose_name_plural': 'Chamados'},
        ),
        migrations.AlterField(
            model_name='chamado',
            name='categoria',
            field=models.CharField(choices=[('BUG', 'Bug / Erro'), ('NOVA_IMPLEMENTACAO', 'Nova Implementação'), ('ALTERACAO', 'Alteração'), ('REFATORACAO', 'Refatoração'), ('DEVOPS', 'DevOps / Infra')], max_length=20),
        ),
        migrations.AlterField(
            model_name='chamado',
            name='prioridade',
            field=models.CharField(choices=[('BAIXA', 'Baixa'), ('MEDIA', 'Média'), ('ALTA', 'Alta'), ('URGENTE', 'Urgente')], default='MEDIA', max_length=10),
        ),
        migrations.AlterField(
            model_name='chamado',
            name='solicitante',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chamados_solicitados', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='chamado',
            name='status',
            field=models.CharField(choices=[('ABERTO', 'Aberto'), ('EM_ANDAMENTO', 'Em andamento'), ('BLOQUEADO', 'Com Bloqueio'), ('VALIDACAO', 'Aguardando Validação'), ('MIGRACAO', 'Em migração'), ('CONCLUIDO', 'Concluído'), ('DOC_PENDENTE', 'Documentação Pendente')], default='ABERTO', max_length=20),
        ),
        migrations.AlterField(
            model_name='perfil',
            name='tipo',
            field=models.CharField(choices=[('TECNICO', 'Técnico'), ('FUNCIONAL', 'Funcional')], max_length=10),
        ),
        migrations.CreateModel(
            name='HistoricoChamado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.TextField()),
                ('data', models.DateTimeField(auto_now_add=True)),
                ('chamado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historico', to='tickets.chamado')),
                ('usuario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['data'],
            },
        ),
    ]
