# Generated by Django 6.0.2 on 2026-02-08 00:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0002_alter_chamado_options_alter_chamado_categoria_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='perfil',
            options={'verbose_name': 'Perfil', 'verbose_name_plural': 'Perfis'},
        ),
        migrations.AlterField(
            model_name='perfil',
            name='tipo',
            field=models.CharField(choices=[('TECNICO', 'Técnico'), ('FUNCIONAL', 'Funcional')], default='FUNCIONAL', max_length=10),
        ),
    ]
