# Generated by Django 6.0.2 on 2026-02-08 00:37

import django.db.models.deletion
import tickets.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0003_alter_perfil_options_alter_perfil_tipo'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AnexoChamado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('arquivo', models.FileField(upload_to=tickets.models.upload_anexo_path)),
                ('nome_original', models.CharField(max_length=255)),
                ('tamanho', models.IntegerField(help_text='Tamanho em bytes')),
                ('data_upload', models.DateTimeField(auto_now_add=True)),
                ('chamado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='anexos', to='tickets.chamado')),
                ('usuario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Anexo do Chamado',
                'verbose_name_plural': 'Anexos dos Chamados',
                'ordering': ['data_upload'],
            },
        ),
    ]
